### ISSUE TITLE
Integrade apprise to allow for more notification options

### ISSUE THREAD

**Issue by Efocat** [HoloArchivists/hoshinova#28]
Integrate [apprise](https://github.com/caronc/apprise) to enable sending notification to a huge array of platforms (discord, slack, telegram, email, etc.), with minimal configurations needed.

an example config would look like:

```toml
[notifier.apprise]
# array of apprise urls 
# ex. send notification to discord, telegram, pushover, and email
# reference apprise documentation for more options
apprise_urls = [
	"discord://webhook_id/webhook_token",
	"tgram://bottoken/ChatID", 
	"pover://user@token",
	"mailtos://userid:pass@domain.com"]
	
notify_on = ["waiting", "recording", "done", "failed"]
```

the apprise call would look like:
```bash
apprise --title 'Hoshinova' --body 'Recording x' \
   'discord://webhook_id/webhook_token' \
   'tgram://bottoken/ChatID' \
   'pover://user@token' \
   'mailtos://userid:pass@domain.com'
```

Relevant documentations
[URL formats (point users to this)](https://github.com/caronc/apprise#productivity-based-notifications)
[Installation](https://github.com/caronc/apprise#installation)
[CLI usage](https://github.com/caronc/apprise/wiki/CLI_Usage)

v0.2.4
